### ISSUE TITLE
Notice For Contributors

### ISSUE THREAD

**Issue by 3imed-jaberi** [github-tunisia/github-tunisia.github.io#1]
# Some Information For Contributors 
---
## Thank you all for contributing to the `GITHUB TUNISIA` organization and being here. 
![GITHUB-TUNISIA-LOGO](https://user-images.githubusercontent.com/43971542/59965347-cf34c900-950c-11e9-87ef-c2516ba3bc3c.jpg)

## When you contribute do not forget to put your name in the README.md file like this :
![ADD-CONTRIBUTE](https://user-images.githubusercontent.com/43971542/59965205-423d4000-950b-11e9-8bb8-0a36ae1efe64.PNG)

## ~Note :  I will add this night the `GTML.svg`  image.~

**Comment by atefBB** [comment]
@3imed-jaberi <div dir="rtl">هل يمكنني المساعدة؟</div>
